server:
  port: 8088

spring:
  application:
    name: api-driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.84.138:8848
  redis:
    host: 192.168.84.138
    port: 6379
    database: 0

