server:
  port: 8081

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.84.138:8848
  application:
    name: api-passenger
  redis:
    host: 192.168.84.130
    port: 6379
    database: 0
